- name: Create centos image
  hosts: localhost
  become: true
  tasks:
    - name: pull image
      docker_image:
        name: treasureboat/ssh
        source: pull

    - name: build image
      docker_container: 
        name: centos_ssh
        image: treasureboat/ssh
        state: started
        ports: 
          - "22"
          - "80"